name: Triggered flow on pull request 
on:
  push:
    branches:
      - main
jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Azure Machine Learning job
      run: |
        echo "Will add code checks here in next challenge"
